# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Olm0h0s8ZF-EuEKsKb5vSr_pLvnxdt9_
"""

# app.py
# Web app Streamlit tính tổng chiều dài mạng lưới đường (KMU) từ OpenStreetMap
# Dựa trên thuật toán trong notebook của bạn (OSMnx: graph_from_place + basic_stats)

import streamlit as st
import osmnx as ox
import matplotlib.pyplot as plt

# Cấu hình chung cho OSMnx
ox.settings.use_cache = True          # cache để tăng tốc các lần chạy sau
ox.settings.log_console = False

st.set_page_config(page_title="Độ dài mạng lưới đường (OSMnx)", page_icon="🗺️", layout="centered")
st.title("🗺️ Tính tổng chiều dài mạng lưới đường (KMU)")

st.markdown(
    """
Nhập **địa danh** đúng như trên OpenStreetMap, ví dụ:
- `Danang, Vietnam`
- `Ho Chi Minh City, Vietnam`
- `Singapore`

Chọn **network_type** để lọc loại đường muốn lấy.
> Kết quả là tổng chiều dài *street_length_total* từ OSMnx (đổi sang **km**).
    """
)

# ===== Inputs =====
place = st.text_input("Địa danh (place):", value="Danang, Vietnam")
network_type = st.selectbox(
    "Loại mạng lưới (network_type):",
    options=["all", "all_public", "drive", "drive_service", "walk", "bike"],
    index=0,
    help=(
        "• all: tất cả đường (gồm hẻm, service road...)\n"
        "• all_public: chỉ đường công cộng\n"
        "• drive: đường ô tô công cộng (loại trừ service road)\n"
        "• drive_service: bao gồm service road\n"
        "• walk: đường đi bộ\n"
        "• bike: đường cho xe đạp"
    ),
)

# ===== Core logic (cache để tránh tải lại nhiều lần) =====
@st.cache_resource(show_spinner=False)
def load_graph(place_name: str, net_type: str):
    """Tải đồ thị đường của 'place_name' theo 'net_type'."""
    G = ox.graph_from_place(place_name, network_type=net_type)
    return G

def compute_total_km(G) -> float:
    """Tính tổng chiều dài street_length_total (km) từ đồ thị."""
    stats = ox.basic_stats(G, clean_int_tol=15)
    total_km = stats.get("street_length_total", 0.0) / 1000.0
    return total_km

# ===== Action =====
col1, col2 = st.columns([1, 1])
with col1:
    run = st.button("Tải & Tính toán", type="primary")
with col2:
    show_map = st.toggle("Hiển thị bản đồ đồ thị", value=True)

if run:
    if not place.strip():
        st.error("Vui lòng nhập địa danh hợp lệ.")
        st.stop()

    try:
        with st.spinner("Đang tải dữ liệu đường từ OpenStreetMap…"):
            G = load_graph(place, network_type)

        total_km = compute_total_km(G)
        st.success(f"✅ Tổng chiều dài mạng lưới đường (KMU): **{total_km:,.3f} km**")

        if show_map:
            st.caption("Bản đồ đồ thị (minh hoạ nhanh):")
            fig, ax = ox.plot_graph(
                G,
                show=False, close=False,
                node_size=0, edge_linewidth=0.8, bgcolor="white"
            )
            st.pyplot(fig, clear_figure=True)

        with st.expander("Chi tiết & gợi ý"):
            st.markdown(
                "- Nếu báo lỗi **place không hợp lệ**: tra cứu tên chuẩn trên [openstreetmap.org](https://www.openstreetmap.org/) (Search) rồi thử lại.\n"
                "- Khu vực quá rộng (cả quốc gia) có thể tải lâu → nên thu hẹp theo *thành phố/quận/phường*.\n"
                "- Thay đổi `network_type` để tính theo mục đích (ô tô/đi bộ/xe đạp...)."
            )

    except Exception as e:
        st.error("Có lỗi xảy ra khi tải/ tính toán. Chi tiết:")
        st.exception(e)
else:
    st.info("Nhập địa danh và bấm **Tải & Tính toán** để bắt đầu.")
